Fixing theano version to 0.7 due to depreciated function
```
File "/Users/tobyz/Documents/python-venv/folkrnn/lib/python3.6/site-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name 'downsample'
```